container:
  image: google/dart

task:
  matrix:
    - name: Linux Test
      container:
        image: google/dart

      only_if: "changesInclude('graphite_language/**/*.dart')"

      env:
        PACKAGE: graphite_language
        CODECOV_TOKEN: ENCRYPTED[9f6adad90465381118258d1f12b8bde7c91afb0be9af77ec661b7e4bdd0676d1c937a4daae15dcb6209146824b7fa74f]

      test_script: bash tool/run_test.sh
